apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: view-files
spec:
  params:
  - name: source-path
    type: string
  steps:
    - name: view-file-in-repo
      command:
      - /bin/sh
      - -c
      args:
      - |-
        ls -al
      image: registry.redhat.io/rhel8/nodejs-16
      resources: {}
      workingDir: /resources/$(params.source-path)
  workspaces:
  - name: output
    mountPath: /resources